import React, { useState, useEffect, useRef } from 'react';
import { T } from './data/i18n';
import { TERMO } from './data/terminology';
import { CATS, PRIS, BUD, CITIES, PCP } from './data/constants';
import { Ic } from './components/Icons';
import './index.css';

const renderMD=(md)=>{if(!md)return null;return md.split("\n").map((line,i)=>{const t=line.trim();if(!t)return <div key={i} style={{height:8}}/>;if(t.startsWith("### "))return <h3 key={i} style={{fontSize:17,fontWeight:700,color:"#1d1d1f",margin:"20px 0 8px",paddingBottom:6,borderBottom:"1px solid #e5e5ea"}}>{t.slice(4).replace(/\*\*/g,"")}</h3>;if(t.startsWith("## "))return <h2 key={i} style={{fontSize:21,fontWeight:700,color:"#0071e3",margin:"28px 0 10px",fontFamily:"inherit"}}>{t.slice(3).replace(/\*\*/g,"")}</h2>;if(t.startsWith("# "))return <h1 key={i} style={{fontSize:26,fontWeight:700,margin:"20px 0 10px",fontFamily:"inherit"}}>{t.slice(2).replace(/\*\*/g,"")}</h1>;if(t.startsWith("- ")||t.startsWith("* ")){const c=t.replace(/^[-*]\s*/,""),p=c.split(/\*\*(.*?)\*\*/g);return <div key={i} style={{display:"flex",gap:8,marginBottom:5,paddingLeft:4,fontSize:14.5,lineHeight:1.65,color:"#48484a"}}><span style={{color:"#86868b"}}>·</span><span>{p.map((x,j)=>j%2===1?<strong key={j} style={{color:"#1d1d1f"}}>{x}</strong>:x)}</span></div>;}if(t.startsWith("|"))return <div key={i} style={{fontFamily:"'JetBrains Mono'",fontSize:12.5,color:"#48484a",padding:"3px 0",borderBottom:t.includes("---")?"2px solid #d2d2d7":"1px solid #e5e5ea",whiteSpace:"pre",overflowX:"auto"}}>{t}</div>;const p=t.split(/\*\*(.*?)\*\*/g);return <p key={i} style={{fontSize:14.5,lineHeight:1.7,color:"#48484a",margin:"3px 0"}}>{p.map((x,j)=>j%2===1?<strong key={j} style={{color:"#1d1d1f"}}>{x}</strong>:x)}</p>;});};

export default function App(){
const[lang,setLang]=useState("en");const t=(k)=>T[lang]?.[k]||T.en[k]||k;
const[view,setView]=useState("home");
const[city,setCity]=useState("");const[cityQ,setCityQ]=useState("");const[showCD,setShowCD]=useState(false);
const[cat,setCat]=useState(null);const[sub,setSub]=useState("");const[pris,setPris]=useState([]);
const[budget,setBudget]=useState("");const[hh,setHh]=useState("3-4");const[notes,setNotes]=useState("");
const[apiKey,setApiKey]=useState("");const[apiSaved,setApiSaved]=useState(false);
const[loading,setLoading]=useState(false);const[result,setResult]=useState("");const[error,setError]=useState("");
const[catQ,setCatQ]=useState("");const[saved,setSaved]=useState([]);const[compSel,setCompSel]=useState([]);const[labMode,setLabMode]=useState("pc");
const[pcP,setPcP]=useState({});const[pcB,setPcB]=useState("");const[pcU,setPcU]=useState("");const[labN,setLabN]=useState("");
const[qS,setQS]=useState(0);const[qA,setQA]=useState([]);
const[cW,setCW]=useState("");const[cH,setCH]=useState("");const[cR,setCR]=useState("8");
const[dP,setDP]=useState("");const[dPr,setDPr]=useState("");const[showT,setShowT]=useState(false);
const rR=useRef(null);

useEffect(()=>{const k=localStorage.getItem("m_key");if(k){setApiKey(k);setApiSaved(true);}const c=localStorage.getItem("m_city");if(c){setCity(c);setCityQ(c);}const l=localStorage.getItem("m_lang");if(l)setLang(l);const s=localStorage.getItem("m_saved");if(s)setSaved(JSON.parse(s));},[]);
const saveK=()=>{if(apiKey.trim()){localStorage.setItem("m_key",apiKey.trim());setApiSaved(true);}};
const selC=(c)=>{setCity(c);setCityQ(c);setShowCD(false);localStorage.setItem("m_city",c);};
const setL=(l)=>{setLang(l);localStorage.setItem("m_lang",l);};const togC=(r)=>setCompSel(p=>p.includes(r)?p.filter(x=>x!==r):p.length<4?[...p,r]:p);const togS=(r)=>{setSaved(p=>{const isS=p.find(x=>x.name===r.name);const n=isS?p.filter(x=>x.name!==r.name):[...p,r];localStorage.setItem("m_saved",JSON.stringify(n));return n;});};
const togP=(id)=>setPris(p=>p.includes(id)?p.filter(x=>x!==id):p.length<5?[...p,id]:p);
const co=CATS.find(c=>c.id===cat);const bds=BUD[cat]||BUD.default;
const fCi=CITIES.filter(c=>c.toLowerCase().includes(cityQ.toLowerCase())).slice(0,6);
const fCa=CATS.filter(c=>(T[lang]?.[c.tk]||"").toLowerCase().includes(catQ.toLowerCase())||c.sub.some(s=>s.toLowerCase().includes(catQ.toLowerCase())));
const langI=lang==="mr"?"\n\nIMPORTANT: Respond ENTIRELY in Marathi (मराठी). Use Devanagari script. Keep product names, brand names, model numbers in English. All explanations in Marathi. Use simple Marathi a 60-year-old parent can understand.":"";

const callAI=async(prompt)=>{if(!apiKey){setError(lang==="mr"?"कृपया सेटिंग्जमध्ये Gemini API की सेट करा.":"Set your Gemini API key in settings.");return;}setLoading(true);setError("");setResult("");try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt+langI}]}],generationConfig:{temperature:0.7,maxOutputTokens:5000}})});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e?.error?.message||`Error ${r.status}`);}const d=await r.json();const tx=d?.candidates?.[0]?.content?.parts?.[0]?.text;if(!tx)throw new Error("Empty response");setResult(tx);}catch(e){setError(e.message);}finally{setLoading(false);}};

const getRec=()=>{const pl=pris.map((p,i)=>`${i+1}. ${t(PRIS.find(o=>o.id===p)?.l)}`).join(", ");const pr=`You are merit. — India's trusted tech advisor.\n\n**Request:** Best ${sub||""} ${t(co?.tk)} recommendation\n**City:** ${city||"Not specified"} | **Household:** ${hh} members | **Budget:** ${budget||"Flexible"}\n**Priorities:** ${pl||"None"}\n**Notes:** ${notes||"None"}\n\nProvide exactly 7 unbiased product recommendations (1 exact match, 2 all-rounders, 4 alternatives/wildcards).\nYou MUST output ONLY valid JSON exactly matching this structure:\n{\n  "recs": [\n    { "name": "Model", "price": "45000", "badge": "🏆 Best Value", "specs": ["spec 1", "spec 2"], "why": "reason", "cons": "tradeoff" }\n  ],\n  "advice": ["Tip 1", "Tip 2"],\n  "comparison": "A short 2-sentence summary comparing the options."\n}\n\nDo not use Markdown code blocks. Just valid JSON.`;callAI(pr).then(()=>{setView("result");setTimeout(()=>rR.current?.scrollIntoView({behavior:"smooth"}),100);});};

const getLabR=()=>{const ps=Object.entries(pcP).filter(([,v])=>v).map(([k,v])=>`${PCP.find(p=>p.id===k)?.n}: ${v}`).join("\n");const pr=labMode==="pc"?`PC Build advisor. Budget: ${pcB||"Flexible"}, Use: ${pcU||"General"}\nParts:\n${ps||"None"}\nNotes: ${labN||"None"}\n\nProvide: Build Analysis, Recommended Build (₹ prices), Compatibility Check, Performance Estimates, Upgrade Path, Where to Buy, Pro Tips`:labMode==="setup"?`Gaming setup advisor. Budget: ${pcB||"Flexible"}, Use: ${pcU||"General"}\nNotes: ${labN||"None"}\n\nRecommend complete setup with ₹ prices.`:`Home theater advisor. Budget: ${pcB||"Flexible"}, Room: ${labN||"Not specified"}\n\nRecommend TV/audio/streaming with ₹ prices.`;callAI(`You are merit. Lab — advanced advisor. Do DEEP research.\n\n${pr}`).then(()=>{setView("labResult");setTimeout(()=>rR.current?.scrollIntoView({behavior:"smooth"}),100);});};

const runQ=()=>{callAI(`You are merit. Quiz results:\n1. Problem: ${qA[0]||"?"}\n2. For: ${qA[1]||"?"}\n3. Priority: ${qA[2]||"?"}\n4. Budget: ${qA[3]||"?"}\nCity: ${city||"?"}\n\nRespond:\n## You Need: [Category]\n## Top 3 Picks (model, ₹, why, con)\n## Why Not [Alternative]\n## Next Steps`).then(()=>setView("quizResult"));};
const chkD=()=>{callAI(`Deal check: ${dP} at ₹${dPr}, City: ${city||"?"}\n\n## Verdict: [GREAT/FAIR/OVERPRICED/RED FLAG]\n## Price Analysis\n## Red Flags\n## Counter-Offer Script\n## Better Alternatives`).then(()=>setView("dealResult"));};

const mC=cW&&cH?((parseFloat(cW)*parseFloat(cH)*30)/1000*parseFloat(cR||8)).toFixed(0):null;
const termos=TERMO[cat]||TERMO.default||[];
const isH=["home","browse","configure","result"].includes(view),isLa=["lab","labConfig","labResult"].includes(view),isTo=["tools","quiz","quizResult","calc","dealCheck","dealResult"].includes(view);

const scamEN={ac:["Check BEE star rating label physically.","Inverter ACs save 30-50% electricity.","Copper coils outlast aluminium.","Don't pay extra for included installation.","1-ton covers ~120 sq ft."],fridge:["300L+ overkill for 4 people.","Inverter compressors worth it — run 24/7.","Check usable, not gross capacity."],phone:["Sensor size > megapixels.","Check OS update years.","Processor > RAM amount.","Online 10-20% below MRP."]};
const scamMR={ac:["BEE स्टार रेटिंग प्रत्यक्ष तपासा.","इन्व्हर्टर AC ३०-५०% वीज वाचवतो.","कॉपर कॉइल ॲल्युमिनियमपेक्षा चांगले.","समाविष्ट इन्स्टॉलेशनसाठी अतिरिक्त पैसे नको.","१-टन ~१२० चौ.फू. कव्हर करतो."],fridge:["४ जणांसाठी ३००L+ अनावश्यक.","इन्व्हर्टर कंप्रेसर योग्य — २४/७ चालतात.","वापरण्यायोग्य क्षमता तपासा."],phone:["सेन्सर आकार > मेगापिक्सेल.","OS अपडेट वर्षे तपासा.","प्रोसेसर > RAM.","ऑनलाइन MRP पेक्षा १०-२०% कमी."]};
const defEN=["Compare on 3+ platforms.","Check brand site for MRP.","Brand warranties beat third-party.","Read reviews 2-3 months post-launch.","Ask for demo. Refusal = red flag."];
const defMR=["३+ प्लॅटफॉर्मवर तुलना करा.","MRP साठी ब्रँड साइट तपासा.","ब्रँड वॉरंटी तृतीय-पक्षापेक्षा चांगली.","लॉन्चनंतर २-३ महिन्यांचे रिव्ह्यू वाचा.","डेमो मागा. नकार = धोक्याचे चिन्ह."];
const scam=(id)=>lang==="mr"?(scamMR[id]||defMR):(scamEN[id]||defEN);

const quizQs=[{q:t("q1"),o:[t("q1a"),t("q1b"),t("q1c"),t("q1d"),t("q1e"),t("q1f")]},{q:t("q2"),o:[t("q2a"),t("q2b"),t("q2c"),t("q2d"),t("q2e")]},{q:t("q3"),o:[t("q3a"),t("q3b"),t("q3c"),t("q3d"),t("q3e"),t("q3f")]},{q:t("q4"),o:[t("q4a"),t("q4b"),t("q4c"),t("q4d")]}];

const CI=({compact})=>(<div style={{position:"relative"}}><input value={cityQ} onChange={e=>{setCityQ(e.target.value);setShowCD(true);}} onFocus={()=>setShowCD(true)} placeholder={t("yourCity")} style={{width:"100%",padding:compact?"10px 14px":"12px 16px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:15,background:"#f5f5f7",fontFamily:"inherit"}}/>{showCD&&cityQ&&fCi.length>0&&<div style={{position:"absolute",top:"100%",left:0,right:0,background:"#fff",borderRadius:12,border:"1px solid var(--border)",boxShadow:"0 8px 24px rgba(0,0,0,.08)",zIndex:50,marginTop:4,overflow:"hidden"}}>{fCi.map(c=><div key={c} onClick={()=>selC(c)} style={{padding:"10px 14px",cursor:"pointer",fontSize:14,borderBottom:"1px solid #f2f2f7"}} onMouseEnter={e=>e.target.style.background="#f5f5f7"} onMouseLeave={e=>e.target.style.background="#fff"}>{c}</div>)}</div>}</div>);
const Ld=({msg})=>(<div className="card" style={{padding:32,textAlign:"center",marginTop:20}}><div className="loader" style={{display:"flex",gap:6,justifyContent:"center",marginBottom:12}}><span/><span/><span/></div><p style={{color:"var(--sub)",fontSize:15}}>{msg}</p><p style={{color:"var(--sub)",fontSize:13,marginTop:4,opacity:.6}}>{t("takes")}</p></div>);
const EB=()=>error?<div style={{background:"#fff2f2",borderRadius:12,padding:"12px 18px",marginTop:12,border:"1px solid #fecaca",color:"#dc2626",fontSize:14}}>{error}</div>:null;
const ScamBox=({id})=>(<div style={{borderRadius:16,padding:"24px 28px",border:"1.5px solid #d2d2d7",background:"linear-gradient(135deg,#f5f5f7,#eef0f3)",marginTop:24}}><div style={{display:"flex",gap:10,alignItems:"center",marginBottom:16}}><Ic name="shield" size={22} color="#34c759"/><span style={{fontSize:18,fontWeight:700,fontFamily:"inherit"}}>{t("scamT")}</span></div>{scam(id).map((tip,i)=>(<div key={i} style={{display:"flex",gap:10,marginBottom:8,fontSize:14,lineHeight:1.6,color:"#48484a"}}><Ic name="check" size={16} color="#34c759"/><span>{tip}</span></div>))}</div>);
const wts=[[t("wCeil"),"75"],[t("wTv"),"80"],[t("wFr"),"150"],[t("wAc1"),"1000"],[t("wAc15"),"1500"],[t("wGey"),"2000"],[t("wWash"),"500"],[t("wMic"),"1200"]];

let pR=null;try{if(result&&result.includes('"recs"'))pR=JSON.parse(result.replace(/```json/gi,"").replace(/```/g,"").trim());}catch(e){}
return(
<div style={{minHeight:"100vh",background:"var(--bg)"}}>
{/* NAV */}
<nav style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"14px 28px",borderBottom:"1px solid var(--border)",background:"rgba(245,245,247,.8)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",position:"sticky",top:0,zIndex:100}}>
<div onClick={()=>{setView("home");setCatQ("");setError("");}} style={{cursor:"pointer",display:"flex",alignItems:"center",gap:10}}><div style={{width:32,height:32,borderRadius:8,background:"#1d1d1f",display:"grid",placeItems:"center"}}><span style={{color:"#fff",fontSize:16,fontWeight:800,fontFamily:"inherit"}}>m</span></div><span style={{fontFamily:"inherit",fontSize:22,color:"#1d1d1f",letterSpacing:-.5}}>merit.</span></div>
<div style={{display:"flex",gap:4,background:"#e8e8ed",borderRadius:10,padding:3}}>{[["home",t("hmdT")],["browse",t("allCats")],["lab",t("lab")]].map(([v,l])=>(<button key={v} onClick={()=>{setView(v);setError("");}} style={{padding:"7px 16px",borderRadius:8,border:"none",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:"inherit",background:(v==="home"&&isH) || (v==="browse"&&view==="browse")||(v==="lab"&&isLa)||(v==="tools"&&isTo)?"#fff":"transparent",color:"#1d1d1f",boxShadow:(v==="home"&&isH) || (v==="browse"&&view==="browse")||(v==="lab"&&isLa)||(v==="tools"&&isTo)?"0 1px 3px rgba(0,0,0,.1)":"none"}}>{l}</button>))}</div>
<div style={{display:"flex",gap:8,alignItems:"center"}}><button onClick={()=>setView("saved")} style={{padding:"6px 12px",borderRadius:8,border:"1.5px solid var(--border)",background:"#fff",cursor:"pointer",fontSize:13,fontWeight:600,fontFamily:"inherit",color:"var(--text)",display:"flex",alignItems:"center",gap:6}}><Ic name="heart" size={14} color={saved.length>0?"var(--accent)":"var(--sub)"}/> {saved.length}</button><button onClick={()=>setL(lang==="en"?"mr":"en")} style={{padding:"5px 12px",borderRadius:8,border:"1.5px solid var(--border)",background:lang==="mr"?"var(--accentBg)":"#fff",cursor:"pointer",fontSize:13,fontWeight:700,fontFamily:"inherit",color:lang==="mr"?"var(--accent)":"var(--sub)",display:"flex",alignItems:"center",gap:4}}><Ic name="lang" size={14}/>{lang==="mr"?"मरा":"EN"}</button><button onClick={()=>setView("settings")} style={{padding:"6px 12px",borderRadius:8,border:"1.5px solid var(--border)",background:"#fff",cursor:"pointer",fontSize:13,fontWeight:600,fontFamily:"inherit",color:"var(--text)",display:"flex",alignItems:"center",gap:4}}>{city || t("cityLabel")}</button><button onClick={()=>setView("settings")} style={{width:32,height:32,borderRadius:8,border:"1px solid var(--border)",background:"#fff",cursor:"pointer",display:"grid",placeItems:"center",color:"var(--sub)"}}><Ic name="settings" size={16}/></button></div>
</nav>

<div style={{maxWidth:920,margin:"0 auto",padding:"0 24px 80px"}}>
{/* SETTINGS */}

{view==="saved"&&<div className="fade-up" style={{paddingTop:40}}>
  <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:24}}><div style={{display:"flex",alignItems:"center",gap:10}}><Ic name="heart" size={24} color="var(--accent)"/><h2 style={{fontFamily:"inherit",fontSize:28,fontWeight:400}}>Saved Items</h2></div>{compSel.length>1&&<button className="btn btn-p" onClick={()=>setView("compare")} style={{padding:"8px 16px",fontSize:13}}>Compare {compSel.length} Items</button>}</div>
  {saved.length===0?<div className="card" style={{padding:40,textAlign:"center"}}><div style={{color:"var(--sub)",marginBottom:12}}><Ic name="heart" size={32}/></div><h3 style={{fontSize:16,fontWeight:600,marginBottom:8}}>No saved items</h3><p style={{fontSize:14,color:"var(--sub)"}}>Click the heart icon on any product recommendation to save it here for comparison.</p></div>:
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(280px, 1fr))",gap:16}}>
    {saved.map((r,i)=><div key={i} className="card" style={{padding:20,display:"flex",flexDirection:"column",position:"relative",border:compSel.includes(r)?"2px solid var(--accent)":"1px solid var(--border)",cursor:"pointer"}} onClick={()=>togC(r)}>
      <div style={{fontSize:12,fontWeight:700,color:"var(--accent)",marginBottom:8}}>{r.badge}</div>
      <div style={{fontWeight:700,fontSize:16,marginBottom:4,paddingRight:24}}>{r.name}</div>
      <div style={{fontSize:18,fontWeight:800,marginBottom:12}}>₹{parseInt(r.price.toString().replace(/\D/g,'')||"0").toLocaleString()}</div>
      <div style={{background:"#f5f5f7",padding:"10px 14px",borderRadius:8,fontSize:12,marginBottom:12}}>
        {r.specs.slice(0,3).map((s,j)=><div key={j} style={{color:"#48484a",marginBottom:4}}>• {s}</div>)}
      </div>
      <button onClick={()=>togS(r)} style={{position:"absolute",top:16,right:16,background:"transparent",border:"none",cursor:"pointer",padding:4}}><Ic name="heart" size={18} color="var(--accent)"/></button>
    </div>)}
  </div>}
</div>}


{view==="compare"&&<div className="fade-up" style={{paddingTop:40}}>
  <div style={{display:"flex",gap:8,marginBottom:20}}><button className="btn btn-s" onClick={()=>setView("saved")} style={{fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> Back to Saved</button></div>
  <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:24}}><Ic name="compare" size={24} color="var(--accent)"/><h2 style={{fontFamily:"inherit",fontSize:28,fontWeight:400}}>Compare Products</h2></div>
  {compSel.length<2?<div className="card" style={{padding:40,textAlign:"center"}}><div style={{color:"var(--sub)",marginBottom:12}}><Ic name="compare" size={32}/></div><h3 style={{fontSize:16,fontWeight:600,marginBottom:8}}>Select products to compare</h3><p style={{fontSize:14,color:"var(--sub)"}}>Go to your Saved items and click on at least 2 products to compare them side-by-side.</p><button className="btn btn-p" onClick={()=>setView("saved")} style={{marginTop:20}}>Go to Saved</button></div>:
  <div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:600,borderCollapse:"collapse",background:"#fff",borderRadius:16,overflow:"hidden",boxShadow:"0 2px 12px rgba(0,0,0,0.04)"}}>
    <thead>
      <tr>
        <th style={{padding:"16px",borderBottom:"2px solid var(--border)",background:"#f5f5f7",textAlign:"left",width:120}}>Feature</th>
        {compSel.map((r,i)=><th key={i} style={{padding:"16px",borderBottom:"2px solid var(--border)",background:"#f5f5f7",textAlign:"left",minWidth:200}}>{r.name}</th>)}
      </tr>
    </thead>
    <tbody>
      <tr><td style={{padding:"16px",borderBottom:"1px solid var(--border)",fontWeight:600,color:"var(--sub)"}}>Price</td>{compSel.map((r,i)=><td key={i} style={{padding:"16px",borderBottom:"1px solid var(--border)",fontSize:18,fontWeight:800}}>₹{parseInt(r.price.toString().replace(/\D/g,'')||"0").toLocaleString()}</td>)}</tr>
      <tr><td style={{padding:"16px",borderBottom:"1px solid var(--border)",fontWeight:600,color:"var(--sub)"}}>Badge</td>{compSel.map((r,i)=><td key={i} style={{padding:"16px",borderBottom:"1px solid var(--border)",color:"var(--accent)",fontWeight:600}}>{r.badge}</td>)}</tr>
      <tr><td style={{padding:"16px",borderBottom:"1px solid var(--border)",fontWeight:600,color:"var(--sub)"}}>Specs</td>{compSel.map((r,i)=><td key={i} style={{padding:"16px",borderBottom:"1px solid var(--border)",fontSize:13,lineHeight:1.6}}>{r.specs.map((s,j)=><div key={j}>• {s}</div>)}</td>)}</tr>
      <tr><td style={{padding:"16px",borderBottom:"1px solid var(--border)",fontWeight:600,color:"var(--sub)"}}>Why Buy</td>{compSel.map((r,i)=><td key={i} style={{padding:"16px",borderBottom:"1px solid var(--border)",fontSize:13,lineHeight:1.6}}>{r.why}</td>)}</tr>
      <tr><td style={{padding:"16px",borderBottom:"1px solid var(--border)",fontWeight:600,color:"var(--sub)"}}>Cons</td>{compSel.map((r,i)=><td key={i} style={{padding:"16px",borderBottom:"1px solid var(--border)",fontSize:13,lineHeight:1.6,color:"#dc2626"}}>{r.cons}</td>)}</tr>
    </tbody>
  </table></div>}
</div>}

{view==="settings"&&<div className="fade-up" style={{paddingTop:40}}><h2 style={{fontFamily:"inherit",fontSize:28,fontWeight:400,marginBottom:20}}>{t("settings")}</h2><div className="card" style={{padding:24,marginBottom:16}}><label style={{fontWeight:700,fontSize:15,display:"block",marginBottom:4}}>{t("gemKey")}</label><p style={{fontSize:13,color:"var(--sub)",marginBottom:12}}>{t("gemKeyD")}</p><div style={{display:"flex",gap:8}}><input type="password" value={apiKey} onChange={e=>{setApiKey(e.target.value);setApiSaved(false);}} placeholder="AIza..." style={{flex:1,padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:14,fontFamily:"'JetBrains Mono'",background:"#f5f5f7"}}/><button className="btn btn-p" onClick={saveK} style={{padding:"10px 20px"}}>{apiSaved?t("saved"):t("save")}</button></div></div><div className="card" style={{padding:24,marginBottom:16}}><label style={{fontWeight:700,fontSize:15,display:"block",marginBottom:4}}>{t("cityLabel")}</label><p style={{fontSize:13,color:"var(--sub)",marginBottom:12}}>{t("cityD")}</p><CI/></div><div className="card" style={{padding:24,marginBottom:16}}><label style={{fontWeight:700,fontSize:15,display:"block",marginBottom:4}}>{t("language")}</label><p style={{fontSize:13,color:"var(--sub)",marginBottom:12}}>{t("langD")}</p><div style={{display:"flex",gap:8}}>{[["en","English"],["mr","मराठी"]].map(([k,l])=><button key={k} className={`pill ${lang===k?"active":""}`} onClick={()=>setL(k)} style={{padding:"10px 20px",fontSize:15}}>{l}</button>)}</div></div><button className="btn btn-s" onClick={()=>setView("home")}><Ic name="back" size={16}/> {t("back")}</button></div>}

{/* HOME */}
{view==="home"&&<div className="fade-up"><div style={{textAlign:"center",padding:"80px 0 56px"}}><p style={{fontSize:13,fontWeight:600,color:"var(--accent)",letterSpacing:1.5,textTransform:"uppercase",marginBottom:16}}>{t("heroTag")}</p><h1 className="hero-t" style={{fontFamily:"inherit",fontSize:44,fontWeight:400,lineHeight:1.05,marginBottom:24,letterSpacing:-0.5}}>{t("heroT1")}<br/>{t("heroT2")}<em>{t("heroT2em")}</em>{t("heroT2dot")}</h1><p style={{fontSize:18,color:"var(--sub)",maxWidth:480,margin:"0 auto",lineHeight:1.6}}>{t("heroSub")}</p><button className="btn btn-p" onClick={()=>{setView("quiz");setQS(0);setQA([]);}} style={{marginTop:36,padding:"16px 36px",fontSize:16,borderRadius:24,boxShadow:"0 8px 24px rgba(0,113,227,.25)"}}>{t("helpDecide")}</button></div>
{!apiSaved&&<div className="card" style={{padding:"18px 24px",marginBottom:32,display:"flex",alignItems:"center",gap:16,flexWrap:"wrap",borderColor:"var(--accent)",borderStyle:"dashed"}}><div style={{flex:1,minWidth:200}}><div style={{fontWeight:700,fontSize:14}}>{t("oneTime")}</div><div style={{fontSize:13,color:"var(--sub)"}}>{t("oneTimeD")}</div></div><button className="btn btn-p" onClick={()=>setView("settings")} style={{padding:"8px 18px",fontSize:13}}>{t("setUp")}</button></div>}
</div>}

{view==="browse"&&<div className="fade-up" style={{paddingTop:32}}>
<div style={{position:"relative",marginBottom:32}}><div style={{position:"absolute",left:16,top:"50%",transform:"translateY(-50%)",color:"var(--sub)"}}><Ic name="search" size={18}/></div><input value={catQ} onChange={e=>setCatQ(e.target.value)} placeholder={t("searchPH")} style={{width:"100%",padding:"16px 16px 16px 48px",borderRadius:16,border:"1.5px solid var(--border)",fontSize:16,background:"#fff",boxShadow:"0 2px 12px rgba(0,0,0,.03)"}}/></div>
<div className="grid-3" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16}}>{fCa.map((c,i)=><div key={c.id} className="card" onClick={()=>{setCat(c.id);setView("configure");setSub("");setPris([]);setBudget("");setNotes("");setResult("");setError("");setShowT(false);}} style={{padding:"24px 20px",cursor:"pointer",animation:`fadeUp .4s ease ${i*.02}s both`,display:"flex",flexDirection:"column",height:"100%",justifyContent:"space-between"}}><div style={{display:"flex",flexDirection:"column",alignItems:"flex-start"}}><div style={{color:"var(--accent)",marginBottom:14}}><Ic name={c.icon} size={28}/></div><div style={{fontWeight:700,fontSize:16,marginBottom:6}}>{t(c.tk)}</div></div><div style={{fontSize:13,color:"var(--sub)",lineHeight:1.5}}>{c.sub.slice(0,3).join(" · ")}</div></div>)}</div>
<div style={{display:"flex",justifyContent:"center",gap:32,padding:"56px 0 0",flexWrap:"wrap"}}>{[["shield",t("noBias")],["zap",t("aiPow")],["check",t("indSpec")]].map(([ic,l])=><div key={l} style={{display:"flex",alignItems:"center",gap:8,fontSize:14,color:"var(--sub)",fontWeight:500}}><Ic name={ic} size={16}/>{l}</div>)}</div></div>}

{/* CONFIGURE */}
{view==="configure"&&co&&<div className="fade-up" style={{paddingTop:28}}>
<button className="btn btn-s" onClick={()=>{setView("home");setCatQ("");}} style={{marginBottom:20,padding:"8px 16px",fontSize:13}}><Ic name="back" size={14}/> {t("allCats")}</button>
<div style={{display:"flex",alignItems:"center",gap:14,marginBottom:28}}><div style={{width:48,height:48,borderRadius:12,background:"var(--accentBg)",display:"grid",placeItems:"center",color:"var(--accent)"}}><Ic name={co.icon} size={26}/></div><div><div style={{fontSize:12,fontWeight:700,color:"var(--accent)",letterSpacing:1,textTransform:"uppercase",marginBottom:4}}>{t("step")} 2 {t("of")} 3</div><h2 style={{fontFamily:"inherit",fontSize:26,fontWeight:400}}>{t(co.tk)}</h2><p style={{fontSize:14,color:"var(--sub)"}}>{t("configPrefs")}</p></div></div>
<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,marginBottom:4,display:"block"}}>{t("typeL")}</label><p style={{fontSize:12,color:"var(--sub)",marginBottom:10}}>{t("typeD")}</p><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{co.sub.map(s=><button key={s} className={`pill ${sub===s?"active":""}`} onClick={()=>setSub(sub===s?"":s)}>{s}</button>)}</div></div>
<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,marginBottom:4,display:"block"}}>{t("whatMat")} <span style={{color:"var(--accent)"}}>*</span></label><p style={{fontSize:12,color:"var(--sub)",marginBottom:10}}>{t("priD")}</p><div className="grid-2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{PRIS.map(o=>{const idx=pris.indexOf(o.id);return <div key={o.id} className={`pill ${idx!==-1?"active":""}`} onClick={()=>togP(o.id)} style={{padding:"10px 14px",display:"flex",alignItems:"center",gap:10,borderRadius:10}}>{idx!==-1&&<span style={{width:22,height:22,borderRadius:6,background:"var(--accent)",color:"#fff",fontSize:12,fontWeight:700,display:"grid",placeItems:"center",flexShrink:0}}>{idx+1}</span>}<div><div style={{fontWeight:600,fontSize:14}}>{t(o.l)}</div><div style={{fontSize:12,color:"var(--sub)"}}>{t(o.d)}</div></div></div>;})}</div></div>
<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,marginBottom:10,display:"block"}}>{t("budgetL")}</label><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{bds.map(b=><button key={b} className={`pill ${budget===b?"active":""}`} onClick={()=>setBudget(budget===b?"":b)}>{b}</button>)}</div></div>
<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,marginBottom:10,display:"block"}}>{t("householdL")}</label><div style={{display:"flex",gap:8}}>{["1-2","3-4","5-6","7+"].map(s=><button key={s} className={`pill ${hh===s?"active":""}`} onClick={()=>setHh(s)}>{s} {t("members")}</button>)}</div></div>
<div className="card" style={{padding:22,marginBottom:20}}><label style={{fontWeight:700,fontSize:14,marginBottom:4,display:"block"}}>{t("anyElse")}</label><p style={{fontSize:12,color:"var(--sub)",marginBottom:10}}>{t("anyElseD")}</p><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} placeholder={t("optDet")} style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:14,resize:"vertical",background:"#f5f5f7",fontFamily:"inherit"}}/></div>
<EB/><div style={{display:"flex",gap:10,alignItems:"center"}}><button className="btn btn-p" disabled={pris.length===0||loading} onClick={getRec}>{loading?t("analyzing"):t("getRec")}</button>{pris.length===0&&<span style={{fontSize:13,color:"var(--sub)"}}>{t("selPri")}</span>}</div>
{loading&&<Ld msg={`${t("finding")} ${city||"you"}...`}/>}<ScamBox id={cat}/></div>}

{/* RESULT */}
{view==="result"&&<div ref={rR} className="fade-up" style={{paddingTop:28}}>
<div style={{display:"flex",gap:8,marginBottom:20}}><button className="btn btn-s" onClick={()=>setView("configure")} style={{fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("adjust")}</button><button className="btn btn-s" onClick={()=>{setView("home");setCatQ("");}} style={{fontSize:13,padding:"8px 16px"}}>{t("newSearch")}</button></div>
<div style={{fontSize:12,fontWeight:700,color:"var(--accent)",letterSpacing:1,textTransform:"uppercase",marginBottom:12}}>{t("step")} 3 {t("of")} 3</div><div className="card" style={{padding:"14px 20px",marginBottom:20,display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><Ic name={co?.icon} size={24} color="var(--accent)"/><div style={{flex:1}}><span style={{fontWeight:700,fontSize:15}}>{t(co?.tk)}</span>{sub&&<span style={{color:"var(--sub)",fontSize:14}}> · {sub}</span>}<div style={{fontSize:12,color:"var(--sub)"}}>{city&&`${city} · `}{budget&&`${budget} · `}{hh} {t("members")}</div></div></div>
{pR&&pR.recs?(
<div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(280px, 1fr))",gap:16,marginBottom:24}}>
    {pR.recs.map((r,i)=><div key={i} className="card" style={{padding:20,display:"flex",flexDirection:"column",position:"relative",transition:"transform 0.2s, box-shadow 0.2s"}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-4px)";e.currentTarget.style.boxShadow="0 12px 32px rgba(0,0,0,0.1)";}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="none";}}>
      <div style={{fontSize:12,fontWeight:700,color:"var(--accent)",marginBottom:8}}>{r.badge}</div>
      <div style={{fontWeight:700,fontSize:16,marginBottom:4,paddingRight:24}}>{r.name}</div>
      <div style={{fontSize:18,fontWeight:800,marginBottom:12}}>₹{parseInt(r.price.toString().replace(/\D/g,'')||"0").toLocaleString()}</div>
      <div style={{fontSize:13,color:"var(--sub)",marginBottom:12,flex:1}}>{r.why}</div>
      <div style={{background:"#f5f5f7",padding:"10px 14px",borderRadius:8,fontSize:12,marginBottom:12}}>
        {r.specs.slice(0,3).map((s,j)=><div key={j} style={{color:"#48484a",marginBottom:4}}>• {s}</div>)}
      </div>
      <div style={{fontSize:12,color:"#dc2626",lineHeight:1.4}}><strong>Cons:</strong> {r.cons}</div>
      <button onClick={()=>togS(r)} style={{position:"absolute",top:16,right:16,background:"transparent",border:"none",cursor:"pointer",padding:4}}><Ic name="heart" size={18} color={saved.find(x=>x.name===r.name)?"var(--accent)":"var(--border)"}/></button>
    </div>)}
  </div>
  <div className="card" style={{padding:24}}>
    <h3 style={{fontSize:16,fontWeight:700,marginBottom:10}}>Expert Verdict</h3><p style={{fontSize:14,lineHeight:1.6,color:"var(--sub)"}}>{pR.comparison}</p>
    <h3 style={{fontSize:16,fontWeight:700,marginTop:20,marginBottom:10}}>Buying Advice</h3><ul style={{paddingLeft:20,fontSize:14,lineHeight:1.6,color:"var(--sub)"}}>{pR.advice.map((a,i)=><li key={i} style={{marginBottom:6}}>{a}</li>)}</ul>
  </div>
</div>
):<div className="card" style={{padding:"28px 24px",lineHeight:1.7}}>{renderMD(result)}</div>}
{/* TERMINOLOGY */}
{termos.length>0&&<div style={{marginTop:24}}><button onClick={()=>setShowT(!showT)} className="card" style={{width:"100%",padding:"18px 24px",cursor:"pointer",display:"flex",alignItems:"center",gap:12,border:"1.5px solid var(--accent)",background:showT?"var(--accentBg)":"white"}}><Ic name="book" size={22} color="var(--accent)"/><div style={{flex:1,textAlign:"left"}}><div style={{fontWeight:700,fontSize:16,color:"var(--accent)"}}>{t("termoT")}</div><div style={{fontSize:13,color:"var(--sub)"}}>{t("termoSub")}</div></div><div style={{transform:showT?"rotate(90deg)":"rotate(0)",transition:"transform .2s"}}><Ic name="arrow" size={18} color="var(--accent)"/></div></button>
{showT&&<div style={{marginTop:12,animation:"fadeUp .3s ease"}}>{termos.map((tm,i)=><div key={i} className="termo-card"><div style={{fontWeight:700,fontSize:15,color:"#1d1d1f",marginBottom:4}}>{lang==="mr"?(tm.tm||tm.t):tm.t}</div><div style={{fontSize:14,lineHeight:1.65,color:"#48484a"}}>{lang==="mr"?tm.mr:tm.en}</div></div>)}</div>}</div>}
<ScamBox id={cat}/><p style={{textAlign:"center",color:"var(--sub)",fontSize:12,padding:"24px 0"}}>{t("aiDisc")}</p></div>}

{/* LAB */}
{view==="lab"&&<div className="fade-up dark" style={{paddingTop:36,margin:"0 -24px",padding:"36px 24px 48px",minHeight:"80vh"}}><p style={{fontSize:12,fontWeight:600,color:"var(--accent)",letterSpacing:1.5,textTransform:"uppercase",marginBottom:8}}>{t("labTag")}</p><h1 style={{fontFamily:"inherit",fontSize:32,fontWeight:400,color:"#f5f5f7",marginBottom:8}}>{t("labT")}</h1><p style={{fontSize:16,color:"var(--darkSub)",marginBottom:32}}>{t("labSub")}</p>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,marginBottom:32}}>{[{id:"pc",ic:"pc",n:t("pcB"),d:t("pcBD")},{id:"setup",ic:"setup",n:t("gsB"),d:t("gsBD")},{id:"theater",ic:"theater",n:t("htB"),d:t("htBD")}].map(m=><div key={m.id} className="card" onClick={()=>{setLabMode(m.id);setView("labConfig");setPcP({});setPcB("");setPcU("");setLabN("");setResult("");setError("");}} style={{padding:22,cursor:"pointer"}}><div style={{color:"var(--accent)",marginBottom:12}}><Ic name={m.ic} size={28}/></div><div style={{fontWeight:700,fontSize:16,marginBottom:4,color:"#f5f5f7"}}>{m.n}</div><div style={{fontSize:13,color:"var(--darkSub)",lineHeight:1.5}}>{m.d}</div><div style={{marginTop:12,color:"var(--accent)",fontSize:13,fontWeight:600,display:"flex",alignItems:"center",gap:4}}>{t("configure")} <Ic name="arrow" size={14}/></div></div>)}</div></div>}

{/* LAB CONFIG */}
{view==="labConfig"&&<div className="fade-up dark" style={{margin:"0 -24px",padding:"28px 24px 48px",minHeight:"80vh"}}>
<button className="btn btn-s" onClick={()=>setView("lab")} style={{marginBottom:20,fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("lab")}</button>
<h2 style={{fontFamily:"inherit",fontSize:28,fontWeight:400,color:"#f5f5f7",marginBottom:24}}>{labMode==="pc"?t("pcB"):labMode==="setup"?t("gsB"):t("htB")}</h2>
{labMode==="pc"&&<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,color:"#f5f5f7",display:"block",marginBottom:4}}>{t("partsC")}</label><p style={{fontSize:12,color:"var(--darkSub)",marginBottom:14}}>{t("partsCd")}</p><div style={{display:"flex",flexDirection:"column",gap:8}}>{PCP.map(p=><div key={p.id}><label style={{fontSize:12,color:"var(--darkSub)",fontWeight:600,marginBottom:3,display:"block"}}>{lang==="mr"?p.nm:p.n}</label><input value={pcP[p.id]||""} onChange={e=>setPcP({...pcP,[p.id]:e.target.value})} placeholder={p.ph} style={{width:"100%",padding:"8px 12px",borderRadius:8,border:"1.5px solid var(--darkBorder)",fontSize:13,background:"#1c1c1e",color:"#f5f5f7",fontFamily:"inherit"}}/></div>)}</div></div>}
<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,color:"#f5f5f7",display:"block",marginBottom:10}}>{t("totBudget")}</label><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{["Under ₹50K","₹50K–80K","₹80K–1.2L","₹1.2L–2L","₹2L+","No limit"].map(b=><button key={b} className={`pill ${pcB===b?"active":""}`} onClick={()=>setPcB(pcB===b?"":b)}>{b}</button>)}</div></div>
<div className="card" style={{padding:22,marginBottom:14}}><label style={{fontWeight:700,fontSize:14,color:"#f5f5f7",display:"block",marginBottom:10}}>{t("priUse")}</label><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{(labMode==="pc"?["Gaming (1080p)","Gaming (1440p)","Gaming (4K)","Video Editing","3D Rendering","Streaming","Programming","General"]:labMode==="setup"?["Competitive FPS","RPG/Story","Sim Racing","Streaming + Gaming","Casual + Work"]:["Movies","Sports","Music","Gaming","All-rounder"]).map(u=><button key={u} className={`pill ${pcU===u?"active":""}`} onClick={()=>setPcU(pcU===u?"":u)}>{u}</button>)}</div></div>
<div className="card" style={{padding:22,marginBottom:20}}><label style={{fontWeight:700,fontSize:14,color:"#f5f5f7",display:"block",marginBottom:6}}>{labMode==="theater"?t("roomDet"):t("addNotes")}</label><textarea value={labN} onChange={e=>setLabN(e.target.value)} rows={2} style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--darkBorder)",fontSize:14,resize:"vertical",background:"#1c1c1e",color:"#f5f5f7",fontFamily:"inherit"}}/></div>
<EB/><button className="btn btn-p" disabled={loading} onClick={getLabR}>{loading?t("deepDive"):t("runDeep")}</button>{loading&&<Ld msg={t("runAnal")}/>}</div>}

{/* LAB RESULT */}
{view==="labResult"&&<div ref={rR} className="fade-up dark" style={{margin:"0 -24px",padding:"28px 24px 48px",minHeight:"80vh"}}><div style={{display:"flex",gap:8,marginBottom:20}}><button className="btn btn-s" onClick={()=>setView("labConfig")} style={{fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("adjust")}</button><button className="btn btn-s" onClick={()=>setView("lab")} style={{fontSize:13,padding:"8px 16px"}}>{t("labHome")}</button></div><div className="card" style={{padding:"28px 24px",lineHeight:1.7}}><div style={{color:"#f5f5f7"}}>{renderMD(result)}</div></div><p style={{textAlign:"center",color:"var(--darkSub)",fontSize:12,padding:"24px 0"}}>{t("labDisc")}</p></div>}

{/* TOOLS */}
{view==="tools"&&<div className="fade-up" style={{paddingTop:40}}><h2 style={{fontFamily:"inherit",fontSize:28,fontWeight:400,marginBottom:8}}>{t("toolsT")}</h2><p style={{fontSize:16,color:"var(--sub)",marginBottom:28}}>{t("toolsSub")}</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{[{i:"quiz",n:t("hmdT"),d:t("hmdD"),a:()=>{setView("quiz");setQS(0);setQA([]);setResult("");setError("");}},{i:"calc",n:t("elCalc"),d:t("elCalcD"),a:()=>{setView("calc");setCW("");setCH("");}},{i:"deal",n:t("dealC"),d:t("dealCD"),a:()=>{setView("dealCheck");setDP("");setDPr("");setResult("");setError("");}},{i:"compare",n:t("compP"),d:t("compPD"),a:()=>{setView("compare");setCompSel([]);}}].map(x=><div key={x.n} className="card" onClick={x.a||undefined} style={{padding:22,cursor:x.a?"pointer":"default",opacity:x.a?1:.5}}><div style={{color:"var(--accent)",marginBottom:10}}><Ic name={x.i} size={24}/></div><div style={{fontWeight:700,fontSize:15,marginBottom:4}}>{x.n}</div><div style={{fontSize:13,color:"var(--sub)",lineHeight:1.5}}>{x.d}</div></div>)}</div></div>}

{/* QUIZ */}
{view==="quiz"&&<div className="fade-up" style={{paddingTop:40}}><button className="btn btn-s" onClick={()=>setView("tools")} style={{marginBottom:20,fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("tools")}</button><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><Ic name="quiz" size={24} color="var(--accent)"/><h2 style={{fontFamily:"inherit",fontSize:26,fontWeight:400}}>{t("hmdT")}</h2></div><p style={{color:"var(--sub)",fontSize:14,marginBottom:24}}>{t("question")} {qS+1} {t("of")} {quizQs.length}</p><div style={{height:3,background:"#e5e5ea",borderRadius:2,marginBottom:28}}><div style={{height:"100%",background:"var(--accent)",borderRadius:2,width:`${((qS+1)/quizQs.length)*100}%`,transition:"width .3s"}}/></div>
<div className="card" style={{padding:28}}><h3 style={{fontSize:20,fontWeight:600,marginBottom:20}}>{quizQs[qS].q}</h3><div style={{display:"flex",flexDirection:"column",gap:8}}>{quizQs[qS].o.map(o=><button key={o} className={`pill ${qA[qS]===o?"active":""}`} onClick={()=>{const a=[...qA];a[qS]=o;setQA(a);if(qS<quizQs.length-1)setTimeout(()=>setQS(qS+1),200);}} style={{padding:"14px 18px",textAlign:"left",fontSize:15,borderRadius:10}}>{o}</button>)}</div></div>
<div style={{display:"flex",gap:8,marginTop:20}}>{qS>0&&<button className="btn btn-s" onClick={()=>setQS(qS-1)}>{t("prev")}</button>}{qS===quizQs.length-1&&qA[qS]&&<button className="btn btn-p" disabled={loading} onClick={runQ}>{loading?t("thinking"):t("getRec2")}</button>}</div><EB/>{loading&&<Ld msg={t("figuring")}/>}</div>}

{view==="quizResult"&&<div className="fade-up" style={{paddingTop:28}}><div style={{display:"flex",gap:8,marginBottom:20}}><button className="btn btn-s" onClick={()=>{setView("quiz");setQS(0);}} style={{fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("retake")}</button><button className="btn btn-s" onClick={()=>setView("home")} style={{fontSize:13,padding:"8px 16px"}}>{t("browseAll")}</button></div><div className="card" style={{padding:"28px 24px",lineHeight:1.7}}>{renderMD(result)}</div></div>}

{/* CALC */}
{view==="calc"&&<div className="fade-up" style={{paddingTop:40}}><button className="btn btn-s" onClick={()=>setView("tools")} style={{marginBottom:20,fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("tools")}</button><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:24}}><Ic name="zap" size={24} color="var(--accent)"/><h2 style={{fontFamily:"inherit",fontSize:26,fontWeight:400}}>{t("calcT")}</h2></div><div className="card" style={{padding:24}}>
<div style={{marginBottom:16}}><label style={{fontWeight:600,fontSize:14,display:"block",marginBottom:6}}>{t("wattage")}</label><input type="number" value={cW} onChange={e=>setCW(e.target.value)} placeholder={t("wattPH")} style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:15,background:"#f5f5f7",fontFamily:"inherit"}}/><div style={{fontSize:12,color:"var(--sub)",marginTop:4}}>{t("wattH")}</div></div>
<div style={{marginBottom:16}}><label style={{fontWeight:600,fontSize:14,display:"block",marginBottom:6}}>{t("hrsDay")}</label><input type="number" value={cH} onChange={e=>setCH(e.target.value)} placeholder={t("hrsPH")} style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:15,background:"#f5f5f7",fontFamily:"inherit"}}/></div>
<div style={{marginBottom:20}}><label style={{fontWeight:600,fontSize:14,display:"block",marginBottom:6}}>{t("elRate")}</label><input type="number" value={cR} onChange={e=>setCR(e.target.value)} placeholder="8" style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:15,background:"#f5f5f7",fontFamily:"inherit"}}/><div style={{fontSize:12,color:"var(--sub)",marginTop:4}}>{t("rateH")}</div></div>
{mC&&<div style={{background:"var(--accentBg)",borderRadius:14,padding:"20px 24px",textAlign:"center"}}><div style={{fontSize:13,color:"var(--accent)",fontWeight:600,marginBottom:4}}>{t("estMonth")}</div><div style={{fontSize:32,fontWeight:800,color:"var(--accent)",fontFamily:"inherit"}}>₹{parseInt(mC).toLocaleString()}</div><div style={{fontSize:13,color:"var(--sub)",marginTop:8}}>{cW}W × {cH}hrs × 30 ÷ 1000 × ₹{cR} = <strong>₹{mC}/{t("month")}</strong></div><div style={{fontSize:13,color:"var(--sub)",marginTop:4}}>{t("yearly")}: <strong>₹{(parseInt(mC)*12).toLocaleString()}</strong></div></div>}
</div><div className="card" style={{padding:20,marginTop:14}}><div style={{fontWeight:700,fontSize:14,marginBottom:10}}>{t("comWatt")}</div><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{wts.map(([n,w])=><button key={n} className="pill" onClick={()=>setCW(w)} style={{fontSize:12,padding:"5px 10px"}}>{n}: {w}W</button>)}</div></div></div>}

{/* DEAL */}
{view==="dealCheck"&&<div className="fade-up" style={{paddingTop:40}}><button className="btn btn-s" onClick={()=>setView("tools")} style={{marginBottom:20,fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("tools")}</button><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:24}}><Ic name="deal" size={24} color="var(--accent)"/><h2 style={{fontFamily:"inherit",fontSize:26,fontWeight:400}}>{t("dealT")}</h2></div><div className="card" style={{padding:24}}><p style={{fontSize:14,color:"var(--sub)",marginBottom:20}}>{t("dealSub")}</p><div style={{marginBottom:16}}><label style={{fontWeight:600,fontSize:14,display:"block",marginBottom:6}}>{t("prodName")}</label><input value={dP} onChange={e=>setDP(e.target.value)} placeholder={t("prodPH")} style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:15,background:"#f5f5f7",fontFamily:"inherit"}}/></div><div style={{marginBottom:20}}><label style={{fontWeight:600,fontSize:14,display:"block",marginBottom:6}}>{t("priceQ")}</label><input type="number" value={dPr} onChange={e=>setDPr(e.target.value)} placeholder={t("pricePH")} style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid var(--border)",fontSize:15,background:"#f5f5f7",fontFamily:"inherit"}}/></div><EB/><button className="btn btn-p" disabled={!dP||!dPr||loading} onClick={chkD}>{loading?t("checking"):t("verDeal")}</button></div>{loading&&<Ld msg={t("crossCheck")}/>}</div>}

{view==="dealResult"&&<div className="fade-up" style={{paddingTop:28}}><div style={{display:"flex",gap:8,marginBottom:20}}><button className="btn btn-s" onClick={()=>setView("dealCheck")} style={{fontSize:13,padding:"8px 16px"}}><Ic name="back" size={14}/> {t("checkAn")}</button></div><div className="card" style={{padding:"14px 20px",marginBottom:16,display:"flex",alignItems:"center",gap:10}}><Ic name="deal" size={20} color="var(--accent)"/><div><strong>{dP}</strong> — <strong>₹{parseInt(dPr).toLocaleString()}</strong></div></div><div className="card" style={{padding:"28px 24px",lineHeight:1.7}}>{renderMD(result)}</div></div>}
</div></div>);
}
